Fix Error TS4023 and eslint warnings
- Fix typescript error TS4023 is to export the Converter class. This error
happens because typescript can't determine it's shape.
- Fix eslint warnings
- Add test case where toBest can actually return null